### PR TITLE
suggested minor changes to MPL support package

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This is a set of some small changes that I suggest be included in the MPL80 pull request against `ros-industrial/motoman`.

If you agree with these, please just merge the PR. This will automatically update your own PR against `ros-industrial/motoman`. If/when your PR is merged, these additional commits can be squashed.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Btw: is the introduced variant the `MPL80` or the `MPL80 II`? If the latter, it would be nice if you could update filenames and references in text and urdfs/xacros as it would be good to be as explicit and accurate as possible with these things.

**Comment by EricMarcil** [comment]
The “II” designation after a robot model, just means that it is coming with a DX200 controller.
The physical arm and kinematic properties are the same as the DX100 controller.
So there is no need to keep filename and reference to both MPL80 and MPL80II, since the change is on the controller side which is capture by setting the “controller” parameter to either “dx100” or “dx200” (which was just added to the motoman_driver in a separate pull request)
The information transmitted in this email is intended solely for the addressee and may contain confidential, proprietary and/or privileged material. Any unauthorized review, distribution or other use of this information is strictly prohibited. If you have received this email in error please contact the sender immediately and delete any and all copies of this message.

**Comment by gavanderhoorn** [comment]
> The “II” designation after a robot model, just means that it is coming with a DX200 controller. 

ok, clear.

> The physical arm and kinematic properties are the same as the DX100 controller. So there is no need to keep filename and reference to both MPL80 and MPL80II, since the change is on the controller side which is capture by setting the “controller” parameter to either “dx100” or “dx200” (which was just added to the motoman_driver in a separate pull request)

agreed.

**Comment by gavanderhoorn** [comment]
The commits in the PR don't change anything wrt naming though. Just to be clear.

**Pull request merged**
